apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: anywhere
  namespace: anywhere
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*.dbee-anywhere.com'
    port:
      name: http
      number: 80
      protocol: HTTP