import { Database } from './database';

export const DATABASES: Database[] = [
  {
    id: 12,
    name: 'Dr. Nice',
    status: 'ready',
    type: 'postgres',
    created_at: '2022-09-01',
    db_name: 'test',
    db_user: 'test',
    db_password: '1234',
    db_capacity: 30,
    db_host: 'localhost',
    db_port: 5432,
  },
  {
    id: 13,
    name: 'Bombasto',
    status: 'processing',
    type: 'postgres',
    created_at: '2022-09-01',
    db_name: 'test',
    db_user: 'test',
    db_password: '1234',
    db_capacity: 30,
    db_host: 'localhost',
    db_port: 5432,
  },
  {
    id: 14,
    name: 'Celeritas',
    status: 'ready',
    type: 'postgres',
    created_at: '2022-09-01',
    db_name: 'test',
    db_user: 'test',
    db_password: '1234',
    db_capacity: 30,
    db_host: 'localhost',
    db_port: 5432,
  },
  {
    id: 15,
    name: 'Magneta',
    status: 'ready',
    type: 'postgres',
    created_at: '2022-09-01',
    db_name: 'test',
    db_user: 'test',
    db_password: '1234',
    db_capacity: 30,
    db_host: 'localhost',
    db_port: 5432,
  },
  {
    id: 16,
    name: 'RubberMan',
    status: 'ready',
    type: 'postgres',
    created_at: '2022-09-01',
    db_name: 'test',
    db_user: 'test',
    db_password: '1234',
    db_capacity: 30,
    db_host: 'localhost',
    db_port: 5432,
  },
  {
    id: 17,
    name: 'Dynama',
    status: 'ready',
    type: 'postgres',
    created_at: '2022-09-01',
    db_name: 'test',
    db_user: 'test',
    db_password: '1234',
    db_capacity: 30,
    db_host: 'localhost',
    db_port: 5432,
  },
  {
    id: 18,
    name: 'Dr. IQ',
    status: 'ready',
    type: 'postgres',
    created_at: '2022-09-01',
    db_name: 'test',
    db_user: 'test',
    db_password: '1234',
    db_capacity: 30,
    db_host: 'localhost',
    db_port: 5432,
  },
  {
    id: 19,
    name: 'Magma',
    status: 'ready',
    type: 'postgres',
    created_at: '2022-09-01',
    db_name: 'test',
    db_user: 'test',
    db_password: '1234',
    db_capacity: 30,
    db_host: 'localhost',
    db_port: 5432,
  },
  {
    id: 20,
    name: 'Tornado',
    status: 'ready',
    type: 'postgres',
    created_at: '2022-09-01',
    db_name: 'test',
    db_user: 'test',
    db_password: '1234',
    db_capacity: 30,
    db_host: 'localhost',
    db_port: 5432,
  },
];
