apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $DATABASE_NAME
  namespace: $NAMESPACE
  labels:
    app: $DATABASE_NAME
    database-uuid: $DATABASE_UUID
    signature: $SIGNATURE
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: ${VOLUME}Gi
